server {
  listen 80;
  listen [::]:80;
  server_name admin.hcasc.cz auth.hcasc.cz kcml0001.hcasc.cz;
  location /.well-known/acme-challenge/ {
    root /var/www/letsencrypt;
  }
  return 308 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name admin.hcasc.cz;
  ssl_certificate /etc/letsencrypt/live/admin.hcasc.cz/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/admin.hcasc.cz/privkey.pem;
  client_max_body_size 1m;
  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:3010;
  }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name auth.hcasc.cz;
  ssl_certificate /etc/letsencrypt/live/admin.hcasc.cz/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/admin.hcasc.cz/privkey.pem;
  client_max_body_size 128k;
  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:3010;
  }
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name kcml0001.hcasc.cz;
  ssl_certificate /etc/letsencrypt/live/admin.hcasc.cz/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/admin.hcasc.cz/privkey.pem;
  client_max_body_size 1m;
  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://127.0.0.1:3010;
  }
}
