import React, { useState } from "react";
import { KeyRound, Plus, RefreshCw, ShieldAlert } from "lucide-react";
import { IconButton, PageHeader } from "./common.js";
import type { Component, ExternalPermission, ExternalPrincipal, ExternalTarget } from "./types.js";

export function ExternalComponentsPage({ principals, targets, permissions, components, role, onRefresh, onCreatePrincipal, onCreateTarget, onRotatePrincipal, onSetPrincipalStatus, onSetTargetStatus, onSetPermission }: {
  principals: ExternalPrincipal[];
  targets: ExternalTarget[];
  permissions: ExternalPermission[];
  components: Component[];
  role: "OWNER" | "ADMIN" | "AUDITOR";
  onRefresh: () => void;
  onCreatePrincipal: (input: { publicId: string; displayName: string; description: string }) => Promise<void>;
  onCreateTarget: (input: { targetKey: string; displayName: string; baseUrl: string; allowedPathPrefixes: string[]; requestTimeoutMs: number; maxRetries: number; circuitFailureThreshold: number; circuitOpenSeconds: number }) => Promise<void>;
  onRotatePrincipal: (principal: ExternalPrincipal) => Promise<{ clientId: string; clientSecret: string; fingerprint: string }>;
  onSetPrincipalStatus: (principal: ExternalPrincipal, status: "ACTIVE" | "DISABLED" | "REVOKED") => Promise<void>;
  onSetTargetStatus: (target: ExternalTarget, status: "ACTIVE" | "DISABLED" | "REVOKED") => Promise<void>;
  onSetPermission: (input: { componentId?: string; externalPrincipalId?: string; externalTargetId: string; routePattern: string; scopeName: string; enabled: boolean }) => Promise<void>;
}) {
  const [principal, setPrincipal] = useState({ publicId: "KCML-EXT-", displayName: "", description: "" });
  const [target, setTarget] = useState({ targetKey: "", displayName: "", baseUrl: "https://", allowedPathPrefixes: "/", requestTimeoutMs: 15000, maxRetries: 1, circuitFailureThreshold: 5, circuitOpenSeconds: 60 });
  const [busy, setBusy] = useState(false);
  const [secret, setSecret] = useState<{ clientId: string; clientSecret: string; fingerprint: string } | null>(null);
  const [permission, setPermission] = useState({ componentId: "", externalPrincipalId: "", externalTargetId: "", routePattern: "/", scopeName: "component.outbound.pulse" });
  async function createPrincipal(event: React.FormEvent) { event.preventDefault(); setBusy(true); try { await onCreatePrincipal(principal); setPrincipal({ publicId: "KCML-EXT-", displayName: "", description: "" }); } finally { setBusy(false); } }
  async function createTarget(event: React.FormEvent) { event.preventDefault(); setBusy(true); try { await onCreateTarget({ ...target, allowedPathPrefixes: target.allowedPathPrefixes.split(",").map((value) => value.trim()).filter(Boolean) }); setTarget({ targetKey: "", displayName: "", baseUrl: "https://", allowedPathPrefixes: "/", requestTimeoutMs: 15000, maxRetries: 1, circuitFailureThreshold: 5, circuitOpenSeconds: 60 }); } finally { setBusy(false); } }
  return <>
    <PageHeader title="Externí strany" description="Spravované identity a canonical cíle pro auditovaný odchozí provoz. URL se vždy ověřuje proti SSRF politice."><IconButton label="Obnovit externí strany" onClick={onRefresh}><RefreshCw size={17} /></IconButton></PageHeader>
    <section className="metric-row"><div className="metric-card neutral"><KeyRound size={22} /><strong>{principals.length}</strong><span>Externí principály</span></div><div className="metric-card neutral"><ShieldAlert size={22} /><strong>{targets.length}</strong><span>Schválené external targets</span></div><div className="metric-card neutral"><strong>{components.length}</strong><span>Komponenty pro oprávnění</span></div></section>
    {role !== "AUDITOR" ? <section className="panel"><div className="panel-head"><h2>Nová externí identita</h2></div><form className="form-grid" onSubmit={(event) => { void createPrincipal(event); }}><label>Client ID<input value={principal.publicId} onChange={(event) => setPrincipal({ ...principal, publicId: event.target.value })} required /></label><label>Název<input value={principal.displayName} onChange={(event) => setPrincipal({ ...principal, displayName: event.target.value })} required /></label><label>Popis<input value={principal.description} onChange={(event) => setPrincipal({ ...principal, description: event.target.value })} /></label><button disabled={busy} type="submit"><Plus size={16} /> Vytvořit principál</button></form></section> : null}
    <section className="panel"><div className="panel-head"><h2>Externí principály</h2></div>{principals.length ? <div className="table-scroll"><table><thead><tr><th>Client ID</th><th>Název</th><th>Stav</th><th>Credentials</th>{role !== "AUDITOR" ? <th>Akce</th> : null}</tr></thead><tbody>{principals.map((entry) => <tr key={entry.id}><td><code>{entry.publicId}</code></td><td>{entry.displayName}<span className="cell-subtitle">{entry.description}</span></td><td><span className={`badge ${entry.status === "ACTIVE" ? "ok" : "danger"}`}>{entry.status}</span></td><td>{entry.credentialCount}</td>{role !== "AUDITOR" ? <td><button className="secondary compact-button" disabled={busy || entry.status !== "ACTIVE"} onClick={() => { void (async () => { setBusy(true); try { setSecret(await onRotatePrincipal(entry)); } finally { setBusy(false); } })(); }}>Rotovat credential</button> <button className="secondary compact-button" disabled={busy || entry.status === "REVOKED"} onClick={() => { void onSetPrincipalStatus(entry, entry.status === "ACTIVE" ? "DISABLED" : "ACTIVE"); }}>{entry.status === "ACTIVE" ? "Zakázat" : "Aktivovat"}</button></td> : null}</tr>)}</tbody></table></div> : <p>Dosud není evidován žádný externí principál.</p>}</section>
    {role !== "AUDITOR" ? <section className="panel"><div className="panel-head"><h2>Nový external target</h2></div><form className="form-grid" onSubmit={(event) => { void createTarget(event); }}><label>Klíč cíle<input value={target.targetKey} onChange={(event) => setTarget({ ...target, targetKey: event.target.value })} required /></label><label>Název<input value={target.displayName} onChange={(event) => setTarget({ ...target, displayName: event.target.value })} required /></label><label>Canonical HTTPS URL<input type="url" value={target.baseUrl} onChange={(event) => setTarget({ ...target, baseUrl: event.target.value })} required /></label><label>Povolené cesty<input value={target.allowedPathPrefixes} onChange={(event) => setTarget({ ...target, allowedPathPrefixes: event.target.value })} required /></label><label>Timeout (ms)<input type="number" min="100" max="60000" value={target.requestTimeoutMs} onChange={(event) => setTarget({ ...target, requestTimeoutMs: Number(event.target.value) })} required /></label><label>Retry pokusy<input type="number" min="0" max="3" value={target.maxRetries} onChange={(event) => setTarget({ ...target, maxRetries: Number(event.target.value) })} required /></label><label>Circuit threshold<input type="number" min="1" max="100" value={target.circuitFailureThreshold} onChange={(event) => setTarget({ ...target, circuitFailureThreshold: Number(event.target.value) })} required /></label><label>Circuit cooldown (s)<input type="number" min="1" max="3600" value={target.circuitOpenSeconds} onChange={(event) => setTarget({ ...target, circuitOpenSeconds: Number(event.target.value) })} required /></label><button disabled={busy} type="submit"><Plus size={16} /> Přidat target</button></form></section> : null}
    <section className="panel"><div className="panel-head"><h2>Schválené external targets</h2></div>{targets.length ? <div className="table-scroll"><table><thead><tr><th>Klíč</th><th>Canonical URL</th><th>Cesty</th><th>Circuit</th><th>Stav</th>{role !== "AUDITOR" ? <th>Akce</th> : null}</tr></thead><tbody>{targets.map((entry) => <tr key={entry.id}><td><strong>{entry.displayName}</strong><span className="cell-subtitle"><code>{entry.targetKey}</code></span></td><td><code>{entry.baseUrl}</code><span className="cell-subtitle">timeout {entry.requestTimeoutMs} ms · retry {entry.maxRetries}</span></td><td>{entry.allowedPathPrefixes.join(", ")}</td><td><span className={`badge ${entry.circuitState === "CLOSED" ? "ok" : "danger"}`}>{entry.circuitState}</span><span className="cell-subtitle">{entry.circuitFailureCount}/{entry.circuitFailureThreshold}, cooldown {entry.circuitOpenSeconds}s</span></td><td><span className={`badge ${entry.status === "ACTIVE" ? "ok" : "danger"}`}>{entry.status}</span></td>{role !== "AUDITOR" ? <td><button className="secondary compact-button" disabled={busy || entry.status === "REVOKED"} onClick={() => { void onSetTargetStatus(entry, entry.status === "ACTIVE" ? "DISABLED" : "ACTIVE"); }}>{entry.status === "ACTIVE" ? "Zakázat" : "Aktivovat"}</button></td> : null}</tr>)}</tbody></table></div> : <p>Dosud není evidován žádný external target.</p>}</section>
    <section className="panel"><div className="panel-head"><h2>Odchozí oprávnění</h2></div>{role !== "AUDITOR" ? <form className="form-grid" onSubmit={(event) => { event.preventDefault(); void onSetPermission({ componentId: permission.componentId || undefined, externalPrincipalId: permission.externalPrincipalId || undefined, externalTargetId: permission.externalTargetId, routePattern: permission.routePattern, scopeName: permission.scopeName, enabled: true }); }}><label>Zdrojová komponenta<select value={permission.componentId} onChange={(event) => setPermission({ ...permission, componentId: event.target.value, externalPrincipalId: "" })}><option value="">Nevybráno</option>{components.map((entry) => <option key={entry.id} value={entry.id}>{entry.code}</option>)}</select></label><label>Externí principál<select value={permission.externalPrincipalId} onChange={(event) => setPermission({ ...permission, externalPrincipalId: event.target.value, componentId: "" })}><option value="">Nevybráno</option>{principals.filter((entry) => entry.status === "ACTIVE").map((entry) => <option key={entry.id} value={entry.id}>{entry.publicId}</option>)}</select></label><label>External target<select value={permission.externalTargetId} onChange={(event) => setPermission({ ...permission, externalTargetId: event.target.value })} required><option value="">Vyberte target</option>{targets.filter((entry) => entry.status === "ACTIVE").map((entry) => <option key={entry.id} value={entry.id}>{entry.targetKey}</option>)}</select></label><label>Route<input value={permission.routePattern} onChange={(event) => setPermission({ ...permission, routePattern: event.target.value })} required /></label><label>Scope<input value={permission.scopeName} onChange={(event) => setPermission({ ...permission, scopeName: event.target.value })} required /></label><button type="submit" disabled={busy || (!permission.componentId && !permission.externalPrincipalId)}>Udělit oprávnění</button></form> : null}{permissions.length ? <div className="table-scroll"><table><thead><tr><th>Zdroj</th><th>Target</th><th>Route</th><th>Scope</th><th>Stav</th></tr></thead><tbody>{permissions.map((entry) => <tr key={entry.id}><td>{entry.component_code ?? entry.external_principal_public_id}</td><td>{entry.target_key}</td><td><code>{entry.route_pattern}</code></td><td>{entry.scope_name}</td><td>{entry.revoked_at ? "Revokováno" : "Aktivní"}</td></tr>)}</tbody></table></div> : <p>Dosud není evidováno žádné externí oprávnění.</p>}</section>
    {secret ? <section className="modal-backdrop" role="presentation"><div className="modal" role="dialog" aria-modal="true" aria-label="Nový credential externího principálu"><h2>Jednorázové zobrazení credentialu</h2><p>Secret se po zavření znovu nezobrazí. Uložte jej do bezpečného klienta.</p><label>Client ID<input readOnly value={secret.clientId} /></label><label>Client secret<input readOnly value={secret.clientSecret} /></label><p>Fingerprint: <code>{secret.fingerprint}</code></p><button onClick={() => setSecret(null)}>Zavřít</button></div></section> : null}
  </>;
}
